CREATE TABLE IF NOT EXISTS Posts(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Text VARCHAR (2048) ,
    Author VARCHAR(128),
    FOREIGN KEY (Author) REFERENCES Users(Username),
    PRIMARY KEY (ID)
)
