CREATE TABLE IF NOT EXISTS Following(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    UserID INT,
    FolloweeID INT,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ,
    FOREIGN KEY (FolloweeID) REFERENCES Users(ID) ,
    PRIMARY KEY (ID)
)
